CREATE TABLE "Set"
(
    id               INTEGER PRIMARY KEY AUTO_INCREMENT,
    baseSetSize      INTEGER,
    block            TEXT,
    booster          LONGTEXT,
    code             VARCHAR(8) UNIQUE NOT NULL,
    isFoilOnly       BOOLEAN           NOT NULL DEFAULT FALSE,
    isForeignOnly    BOOLEAN           NOT NULL DEFAULT FALSE,
    isNonFoilOnly    BOOLEAN           NOT NULL DEFAULT FALSE,
    isOnlineOnly     BOOLEAN           NOT NULL DEFAULT FALSE,
    isPartialPreview BOOLEAN           NOT NULL DEFAULT FALSE,
    keyruneCode      TEXT,
    mcmId            INTEGER,
    mcmIdExtras      INTEGER,
    mcmName          TEXT,
    mtgoCode         TEXT,
    name             TEXT,
    parentCode       TEXT,
    releaseDate      DATE,
    sealedProduct    TEXT,
    tcgplayerGroupId INTEGER,
    totalSetSize     INTEGER,
    type             ENUM ('core', 'masters', 'expansion', 'memorabilia', 'commander', 'starter', 'archenemy', 'box', 'draft_innovation', 'from_the_vault', 'funny', 'duel_deck', 'masterpiece', 'promo', 'premium_deck', 'planechase', 'token', 'vanguard', 'treasure_chest', 'spellbook')
);

CREATE TABLE "Card"
(
    id                       INTEGER PRIMARY KEY AUTO_INCREMENT,
    artist                   TEXT,
    asciiName                TEXT,
    availability             TEXT,
    borderColor              ENUM ('black', 'white', 'borderless', 'silver', 'gold'),
    colorIdentity            TEXT,
    colorIndicator           TEXT,
    colors                   TEXT,
    convertedManaCost        FLOAT,
    duelDeck                 TEXT,
    edhrecRank               INTEGER,
    faceConvertedManaCost    FLOAT,
    faceManaValue            FLOAT,
    faceName                 TEXT,
    finishes                 TEXT,
    flavorName               TEXT,
    flavorText               TEXT,
    frameEffects             TEXT,
    frameVersion             ENUM ('2003', '1993', '2015', '1997', 'future'),
    hand                     TEXT,
    hasAlternativeDeckLimit  BOOLEAN         NOT NULL DEFAULT 0,
    hasContentWarning        BOOLEAN         NOT NULL DEFAULT 0,
    hasFoil                  BOOLEAN         NOT NULL DEFAULT 0,
    hasNonFoil               BOOLEAN         NOT NULL DEFAULT 0,
    isAlternative            BOOLEAN         NOT NULL DEFAULT 0,
    isFullArt                BOOLEAN         NOT NULL DEFAULT 0,
    isOnlineOnly             BOOLEAN         NOT NULL DEFAULT 0,
    isOversized              BOOLEAN         NOT NULL DEFAULT 0,
    isPromo                  BOOLEAN         NOT NULL DEFAULT 0,
    isReprint                BOOLEAN         NOT NULL DEFAULT 0,
    isReserved               BOOLEAN         NOT NULL DEFAULT 0,
    isStarter                BOOLEAN         NOT NULL DEFAULT 0,
    isStorySpotlight         BOOLEAN         NOT NULL DEFAULT 0,
    isTextless               BOOLEAN         NOT NULL DEFAULT 0,
    isTimeshifted            BOOLEAN         NOT NULL DEFAULT 0,
    keywords                 TEXT,
    layout                   ENUM ('normal', 'adventure', 'class', 'aftermath', 'split', 'flip', 'leveler', 'saga', 'transform', 'vanguard', 'meld', 'modal_dfc', 'scheme', 'planar', 'host', 'augment'),
    leadershipSkills         TEXT,
    life                     TEXT,
    loyalty                  TEXT,
    manaCost                 TEXT,
    manaValue                FLOAT,
    mcmId                    TEXT,
    mcmMetaId                TEXT,
    mtgArenaId               TEXT,
    mtgjsonV4Id              TEXT,
    mtgoFoilId               TEXT,
    mtgoId                   TEXT,
    multiverseId             TEXT,
    name                     TEXT,
    number                   TEXT,
    originalReleaseDate      TEXT,
    originalText             TEXT,
    originalType             TEXT,
    otherFaceIds             TEXT,
    power                    TEXT,
    printings                TEXT,
    promoTypes               TEXT,
    purchaseUrls             TEXT,
    rarity                   ENUM ('uncommon', 'common', 'rare', 'mythic', 'special', 'bonus'),
    scryfallId               TEXT,
    scryfallIllustrationId   TEXT,
    scryfallOracleId         TEXT,
    setCode                  TEXT,
    side                     TEXT,
    subtypes                 TEXT,
    supertypes               TEXT,
    tcgplayerEtchedProductId TEXT,
    tcgplayerProductId       TEXT,
    text                     TEXT,
    toughness                TEXT,
    type                     TEXT,
    types                    TEXT,
    uuid                     CHAR(36) UNIQUE NOT NULL,
    variations               TEXT,
    watermark                TEXT
);